// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Debug: verificar se as variáveis estão sendo carregadas
console.log('🔍 Debug Supabase Config:');
console.log('SUPABASE_URL:', SUPABASE_URL);
console.log('SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? '✅ Loaded' : '❌ Missing');
console.log('All env vars:', import.meta.env);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Validação das variáveis de ambiente
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Erro: Variáveis de ambiente do Supabase não encontradas!');
  console.error('SUPABASE_URL:', SUPABASE_URL);
  console.error('SUPABASE_PUBLISHABLE_KEY:', SUPABASE_PUBLISHABLE_KEY ? 'Existe' : 'Não existe');
  throw new Error('Configuração do Supabase incompleta. Verifique as variáveis de ambiente.');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});